package incar.mobile.caring.admin.model

data class Adjuster(
    val id: Int,
    val name: String,
    val company: String,
    val phone: String,
    val officePhone: String?,
    val fax: String?,
    val address: String?,
    val addressDetail: String?,
    val careerYears: Int,
    val regions: List<String>,
    val fields: List<String>,
    val consultingFields: List<String>,
    val email: String?,
    val profileImage: String?,
    val qualifications: List<String>,
    val mainCareer: String?,
    val isVisible: Boolean,
    val reviewScore: Double?,
    val reviewCount: Int,
    val consultingReviewScore: Double?,
    val consultingReviewCount: Int,
    val lat: Double?,
    val lng: Double?,
    val createdAt: String,
    val updatedAt: String,
)
